CREATE MULTISET TABLE AdventureWorksDW2019.AdventureWorksDWBuildVersion ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      DBVersion VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      VersionDate TIMESTAMP(0))
PRIMARY INDEX ( DBVersion );

CREATE MULTISET TABLE AdventureWorksDW2019.DatabaseLog ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      DatabaseLogID INTEGER NOT NULL,
      PostTime TIMESTAMP(0) NOT NULL,
      DatabaseUser VARCHAR(256) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      Event VARCHAR(256) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      Schema VARCHAR(256) CHARACTER SET UNICODE CASESPECIFIC,
      "Object" VARCHAR(256) CHARACTER SET UNICODE CASESPECIFIC, 
PRIMARY KEY ( DatabaseLogID ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimAccount ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      AccountKey INTEGER NOT NULL,
      ParentAccountKey INTEGER,
      AccountCodeAlternateKey INTEGER,
      ParentAccountCodeAlternateKey INTEGER,
      AccountDescription VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      AccountType VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      Operator VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      CustomMembers VARCHAR(600) CHARACTER SET UNICODE CASESPECIFIC,
      ValueType VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      CustomMemberOptions VARCHAR(400) CHARACTER SET UNICODE CASESPECIFIC, 
PRIMARY KEY ( AccountKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimCurrency ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      CurrencyKey INTEGER NOT NULL,
      CurrencyAlternateKey CHAR(6) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      CurrencyName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL, 
PRIMARY KEY ( CurrencyKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimCustomer ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      CustomerKey INTEGER NOT NULL,
      GeographyKey INTEGER,
      CustomerAlternateKey VARCHAR(30) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      "Title" VARCHAR(16) CHARACTER SET UNICODE CASESPECIFIC,
      FirstName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      MiddleName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      LastName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      NameStyle BYTEINT,
      BirthDate DATE FORMAT 'YYYY/MM/DD',
      MaritalStatus CHAR(2) CHARACTER SET UNICODE CASESPECIFIC,
      Suffix VARCHAR(20) CHARACTER SET UNICODE CASESPECIFIC,
      Gender VARCHAR(2) CHARACTER SET UNICODE CASESPECIFIC,
      EmailAddress VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      YearlyIncome DECIMAL(19,4),
      TotalChildren INTEGER,
      NumberChildrenAtHome INTEGER,
      EnglishEducation VARCHAR(80) CHARACTER SET UNICODE CASESPECIFIC,
      SpanishEducation VARCHAR(80) CHARACTER SET UNICODE CASESPECIFIC,
      FrenchEducation VARCHAR(80) CHARACTER SET UNICODE CASESPECIFIC,
      EnglishOccupation VARCHAR(200) CHARACTER SET UNICODE CASESPECIFIC,
      SpanishOccupation VARCHAR(200) CHARACTER SET UNICODE CASESPECIFIC,
      FrenchOccupation VARCHAR(200) CHARACTER SET UNICODE CASESPECIFIC,
      HouseOwnerFlag CHAR(2) CHARACTER SET UNICODE CASESPECIFIC,
      NumberCarsOwned INTEGER,
      AddressLine1 VARCHAR(240) CHARACTER SET UNICODE CASESPECIFIC,
      AddressLine2 VARCHAR(240) CHARACTER SET UNICODE CASESPECIFIC,
      Phone VARCHAR(40) CHARACTER SET UNICODE CASESPECIFIC,
      DateFirstPurchase DATE FORMAT 'YYYY/MM/DD',
      CommuteDistance VARCHAR(30) CHARACTER SET UNICODE CASESPECIFIC, 
PRIMARY KEY ( CustomerKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimDate ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      DateKey INTEGER NOT NULL,
      FullDateAlternateKey DATE FORMAT 'YYYY/MM/DD' NOT NULL,
      DayNumberOfWeek INTEGER NOT NULL,
      EnglishDayNameOfWeek VARCHAR(20) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      SpanishDayNameOfWeek VARCHAR(20) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      FrenchDayNameOfWeek VARCHAR(20) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      DayNumberOfMonth INTEGER NOT NULL,
      DayNumberOfYear SMALLINT NOT NULL,
      WeekNumberOfYear INTEGER NOT NULL,
      EnglishMonthName VARCHAR(20) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      SpanishMonthName VARCHAR(20) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      FrenchMonthName VARCHAR(20) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      MonthNumberOfYear INTEGER NOT NULL,
      CalendarQuarter INTEGER NOT NULL,
      CalendarYear SMALLINT NOT NULL,
      CalendarSemester INTEGER NOT NULL,
      FiscalQuarter INTEGER NOT NULL,
      FiscalYear SMALLINT NOT NULL,
      FiscalSemester INTEGER NOT NULL, 
PRIMARY KEY ( DateKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimDepartmentGroup ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      DepartmentGroupKey INTEGER NOT NULL,
      ParentDepartmentGroupKey INTEGER,
      DepartmentGroupName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC, 
PRIMARY KEY ( DepartmentGroupKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimEmployee ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      EmployeeKey INTEGER NOT NULL,
      ParentEmployeeKey INTEGER,
      EmployeeNationalIDAlternateKey VARCHAR(30) CHARACTER SET UNICODE CASESPECIFIC,
      ParentEmployeeNationalIDAlternateKey VARCHAR(30) CHARACTER SET UNICODE CASESPECIFIC,
      SalesTerritoryKey INTEGER,
      FirstName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      LastName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      MiddleName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      NameStyle BYTEINT NOT NULL,
      "Title" VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      HireDate DATE FORMAT 'YYYY/MM/DD',
      BirthDate DATE FORMAT 'YYYY/MM/DD',
      LoginID VARCHAR(512) CHARACTER SET UNICODE CASESPECIFIC,
      EmailAddress VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      Phone VARCHAR(50) CHARACTER SET UNICODE CASESPECIFIC,
      MaritalStatus CHAR(2) CHARACTER SET UNICODE CASESPECIFIC,
      EmergencyContactName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      EmergencyContactPhone VARCHAR(50) CHARACTER SET UNICODE CASESPECIFIC,
      SalariedFlag BYTEINT,
      Gender CHAR(2) CHARACTER SET UNICODE CASESPECIFIC,
      PayFrequency INTEGER,
      BaseRate DECIMAL(19,4),
      VacationHours SMALLINT,
      SickLeaveHours SMALLINT,
      CurrentFlag BYTEINT NOT NULL,
      SalesPersonFlag BYTEINT NOT NULL,
      DepartmentName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      StartDate DATE FORMAT 'YYYY/MM/DD',
      EndDate DATE FORMAT 'YYYY/MM/DD',
      Status VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC, 
PRIMARY KEY ( EmployeeKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimGeography ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      GeographyKey INTEGER NOT NULL,
      City VARCHAR(60) CHARACTER SET UNICODE CASESPECIFIC,
      StateProvinceCode VARCHAR(6) CHARACTER SET UNICODE CASESPECIFIC,
      StateProvinceName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      CountryRegionCode VARCHAR(6) CHARACTER SET UNICODE CASESPECIFIC,
      EnglishCountryRegionName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      SpanishCountryRegionName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      FrenchCountryRegionName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      PostalCode VARCHAR(30) CHARACTER SET UNICODE CASESPECIFIC,
      SalesTerritoryKey INTEGER,
      IpAddressLocator VARCHAR(30) CHARACTER SET UNICODE CASESPECIFIC, 
PRIMARY KEY ( GeographyKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimOrganization ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      OrganizationKey INTEGER NOT NULL,
      ParentOrganizationKey INTEGER,
      PercentageOfOwnership VARCHAR(32) CHARACTER SET UNICODE CASESPECIFIC,
      OrganizationName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      CurrencyKey INTEGER, 
PRIMARY KEY ( OrganizationKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimProduct ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ProductKey INTEGER NOT NULL,
      ProductAlternateKey VARCHAR(50) CHARACTER SET UNICODE CASESPECIFIC,
      ProductSubcategoryKey INTEGER,
      WeightUnitMeasureCode CHAR(6) CHARACTER SET UNICODE CASESPECIFIC,
      SizeUnitMeasureCode CHAR(6) CHARACTER SET UNICODE CASESPECIFIC,
      EnglishProductName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      SpanishProductName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      FrenchProductName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      StandardCost DECIMAL(19,4),
      FinishedGoodsFlag BYTEINT NOT NULL,
      Color VARCHAR(30) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      SafetyStockLevel SMALLINT,
      ReorderPoint SMALLINT,
      ListPrice DECIMAL(19,4),
      Size VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      SizeRange VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      Weight FLOAT,
      DaysToManufacture INTEGER,
      ProductLine CHAR(4) CHARACTER SET UNICODE CASESPECIFIC,
      DealerPrice DECIMAL(19,4),
      "Class" CHAR(4) CHARACTER SET UNICODE CASESPECIFIC,
      Style CHAR(4) CHARACTER SET UNICODE CASESPECIFIC,
      ModelName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      EnglishDescription VARCHAR(800) CHARACTER SET UNICODE CASESPECIFIC,
      FrenchDescription VARCHAR(800) CHARACTER SET UNICODE CASESPECIFIC,
      ChineseDescription VARCHAR(800) CHARACTER SET UNICODE CASESPECIFIC,
      ArabicDescription VARCHAR(800) CHARACTER SET UNICODE CASESPECIFIC,
      HebrewDescription VARCHAR(800) CHARACTER SET UNICODE CASESPECIFIC,
      ThaiDescription VARCHAR(800) CHARACTER SET UNICODE CASESPECIFIC,
      GermanDescription VARCHAR(800) CHARACTER SET UNICODE CASESPECIFIC,
      JapaneseDescription VARCHAR(800) CHARACTER SET UNICODE CASESPECIFIC,
      TurkishDescription VARCHAR(800) CHARACTER SET UNICODE CASESPECIFIC,
      StartDate TIMESTAMP(0),
      EndDate TIMESTAMP(0),
      Status VARCHAR(14) CHARACTER SET UNICODE CASESPECIFIC, 
PRIMARY KEY ( ProductKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimProductCategory ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ProductCategoryKey INTEGER NOT NULL,
      ProductCategoryAlternateKey INTEGER,
      EnglishProductCategoryName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      SpanishProductCategoryName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      FrenchProductCategoryName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL, 
PRIMARY KEY ( ProductCategoryKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimProductSubcategory ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ProductSubcategoryKey INTEGER NOT NULL,
      ProductSubcategoryAlternateKey INTEGER,
      EnglishProductSubcategoryName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      SpanishProductSubcategoryName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      FrenchProductSubcategoryName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      ProductCategoryKey INTEGER, 
PRIMARY KEY ( ProductSubcategoryKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimPromotion ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      PromotionKey INTEGER NOT NULL,
      PromotionAlternateKey INTEGER,
      EnglishPromotionName VARCHAR(510) CHARACTER SET UNICODE CASESPECIFIC,
      SpanishPromotionName VARCHAR(510) CHARACTER SET UNICODE CASESPECIFIC,
      FrenchPromotionName VARCHAR(510) CHARACTER SET UNICODE CASESPECIFIC,
      DiscountPct FLOAT,
      EnglishPromotionType VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      SpanishPromotionType VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      FrenchPromotionType VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      EnglishPromotionCategory VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      SpanishPromotionCategory VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      FrenchPromotionCategory VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      StartDate TIMESTAMP(0) NOT NULL,
      EndDate TIMESTAMP(0),
      MinQty INTEGER,
      MaxQty INTEGER, 
PRIMARY KEY ( PromotionKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimReseller ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ResellerKey INTEGER NOT NULL,
      GeographyKey INTEGER,
      ResellerAlternateKey VARCHAR(30) CHARACTER SET UNICODE CASESPECIFIC,
      Phone VARCHAR(50) CHARACTER SET UNICODE CASESPECIFIC,
      BusinessType VARCHAR(20) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      ResellerName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      NumberEmployees INTEGER,
      OrderFrequency CHAR(1) CHARACTER SET UNICODE CASESPECIFIC,
      OrderMonth INTEGER,
      FirstOrderYear INTEGER,
      LastOrderYear INTEGER,
      ProductLine VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      AddressLine1 VARCHAR(120) CHARACTER SET UNICODE CASESPECIFIC,
      AddressLine2 VARCHAR(120) CHARACTER SET UNICODE CASESPECIFIC,
      AnnualSales DECIMAL(19,4),
      BankName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      MinPaymentType INTEGER,
      MinPaymentAmount DECIMAL(19,4),
      AnnualRevenue DECIMAL(19,4),
      YearOpened INTEGER, 
PRIMARY KEY ( ResellerKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimSalesReason ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      SalesReasonKey INTEGER NOT NULL,
      SalesReasonAlternateKey INTEGER NOT NULL,
      SalesReasonName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      SalesReasonReasonType VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL, 
PRIMARY KEY ( SalesReasonKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimSalesTerritory ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      SalesTerritoryKey INTEGER NOT NULL,
      SalesTerritoryAlternateKey INTEGER,
      SalesTerritoryRegion VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      SalesTerritoryCountry VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      SalesTerritoryGroup VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC, 
PRIMARY KEY ( SalesTerritoryKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.DimScenario ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ScenarioKey INTEGER NOT NULL,
      ScenarioName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC, 
PRIMARY KEY ( ScenarioKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.FactAdditionalInternationalProductDescription ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ProductKey INTEGER NOT NULL,
      CultureName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL, 
PRIMARY KEY ( ProductKey ,CultureName ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.FactCallCenter ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      FactCallCenterID INTEGER NOT NULL,
      DateKey INTEGER NOT NULL,
      WageType VARCHAR(30) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      Shift VARCHAR(40) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      LevelOneOperators SMALLINT NOT NULL,
      LevelTwoOperators SMALLINT NOT NULL,
      TotalOperators SMALLINT NOT NULL,
      Calls INTEGER NOT NULL,
      AutomaticResponses INTEGER NOT NULL,
      Orders INTEGER NOT NULL,
      IssuesRaised SMALLINT NOT NULL,
      AverageTimePerIssue SMALLINT NOT NULL,
      ServiceGrade FLOAT NOT NULL,
      "Date" TIMESTAMP(0), 
PRIMARY KEY ( FactCallCenterID ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.FactCurrencyRate ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      CurrencyKey INTEGER NOT NULL,
      DateKey INTEGER NOT NULL,
      AverageRate FLOAT NOT NULL,
      EndOfDayRate FLOAT NOT NULL,
      "Date" TIMESTAMP(0), 
PRIMARY KEY ( CurrencyKey ,DateKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.FactFinance ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      FinanceKey INTEGER NOT NULL,
      DateKey INTEGER NOT NULL,
      OrganizationKey INTEGER NOT NULL,
      DepartmentGroupKey INTEGER NOT NULL,
      ScenarioKey INTEGER NOT NULL,
      AccountKey INTEGER NOT NULL,
      Amount FLOAT NOT NULL,
      "Date" TIMESTAMP(0))
PRIMARY INDEX ( FinanceKey );

CREATE MULTISET TABLE AdventureWorksDW2019.FactInternetSales ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ProductKey INTEGER NOT NULL,
      OrderDateKey INTEGER NOT NULL,
      DueDateKey INTEGER NOT NULL,
      ShipDateKey INTEGER NOT NULL,
      CustomerKey INTEGER NOT NULL,
      PromotionKey INTEGER NOT NULL,
      CurrencyKey INTEGER NOT NULL,
      SalesTerritoryKey INTEGER NOT NULL,
      SalesOrderNumber VARCHAR(40) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      SalesOrderLineNumber INTEGER NOT NULL,
      RevisionNumber INTEGER NOT NULL,
      OrderQuantity SMALLINT NOT NULL,
      UnitPrice DECIMAL(19,4) NOT NULL,
      ExtendedAmount DECIMAL(19,4) NOT NULL,
      UnitPriceDiscountPct FLOAT NOT NULL,
      DiscountAmount FLOAT NOT NULL,
      ProductStandardCost DECIMAL(19,4) NOT NULL,
      TotalProductCost DECIMAL(19,4) NOT NULL,
      SalesAmount DECIMAL(19,4) NOT NULL,
      TaxAmt DECIMAL(19,4) NOT NULL,
      Freight DECIMAL(19,4) NOT NULL,
      CarrierTrackingNumber VARCHAR(50) CHARACTER SET UNICODE CASESPECIFIC,
      CustomerPONumber VARCHAR(50) CHARACTER SET UNICODE CASESPECIFIC,
      OrderDate TIMESTAMP(0),
      DueDate TIMESTAMP(0),
      ShipDate TIMESTAMP(0), 
PRIMARY KEY ( SalesOrderNumber ,SalesOrderLineNumber ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.FactInternetSalesReason ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      SalesOrderNumber VARCHAR(40) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      SalesOrderLineNumber INTEGER NOT NULL,
      SalesReasonKey INTEGER NOT NULL, 
PRIMARY KEY ( SalesOrderNumber ,SalesOrderLineNumber ,SalesReasonKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.FactProductInventory ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ProductKey INTEGER NOT NULL,
      DateKey INTEGER NOT NULL,
      MovementDate DATE FORMAT 'YYYY/MM/DD' NOT NULL,
      UnitCost DECIMAL(19,4) NOT NULL,
      UnitsIn INTEGER NOT NULL,
      UnitsOut INTEGER NOT NULL,
      UnitsBalance INTEGER NOT NULL, 
PRIMARY KEY ( ProductKey ,DateKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.FactResellerSales ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ProductKey INTEGER NOT NULL,
      OrderDateKey INTEGER NOT NULL,
      DueDateKey INTEGER NOT NULL,
      ShipDateKey INTEGER NOT NULL,
      ResellerKey INTEGER NOT NULL,
      EmployeeKey INTEGER NOT NULL,
      PromotionKey INTEGER NOT NULL,
      CurrencyKey INTEGER NOT NULL,
      SalesTerritoryKey INTEGER NOT NULL,
      SalesOrderNumber VARCHAR(40) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      SalesOrderLineNumber INTEGER NOT NULL,
      RevisionNumber INTEGER,
      OrderQuantity SMALLINT,
      UnitPrice DECIMAL(19,4),
      ExtendedAmount DECIMAL(19,4),
      UnitPriceDiscountPct FLOAT,
      DiscountAmount FLOAT,
      ProductStandardCost DECIMAL(19,4),
      TotalProductCost DECIMAL(19,4),
      SalesAmount DECIMAL(19,4),
      TaxAmt DECIMAL(19,4),
      Freight DECIMAL(19,4),
      CarrierTrackingNumber VARCHAR(50) CHARACTER SET UNICODE CASESPECIFIC,
      CustomerPONumber VARCHAR(50) CHARACTER SET UNICODE CASESPECIFIC,
      OrderDate TIMESTAMP(0),
      DueDate TIMESTAMP(0),
      ShipDate TIMESTAMP(0), 
PRIMARY KEY ( SalesOrderNumber ,SalesOrderLineNumber ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.FactSalesQuota ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      SalesQuotaKey INTEGER NOT NULL,
      EmployeeKey INTEGER NOT NULL,
      DateKey INTEGER NOT NULL,
      CalendarYear SMALLINT NOT NULL,
      CalendarQuarter INTEGER NOT NULL,
      SalesAmountQuota DECIMAL(19,4) NOT NULL,
      "Date" TIMESTAMP(0), 
PRIMARY KEY ( SalesQuotaKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.FactSurveyResponse ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      SurveyResponseKey INTEGER NOT NULL,
      DateKey INTEGER NOT NULL,
      CustomerKey INTEGER NOT NULL,
      ProductCategoryKey INTEGER NOT NULL,
      EnglishProductCategoryName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      ProductSubcategoryKey INTEGER NOT NULL,
      EnglishProductSubcategoryName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC NOT NULL,
      "Date" TIMESTAMP(0), 
PRIMARY KEY ( SurveyResponseKey ))
;

CREATE MULTISET TABLE AdventureWorksDW2019.NewFactCurrencyRate ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      AverageRate FLOAT,
      CurrencyID VARCHAR(6) CHARACTER SET UNICODE CASESPECIFIC,
      CurrencyDate DATE FORMAT 'YYYY/MM/DD',
      EndOfDayRate FLOAT,
      CurrencyKey INTEGER,
      DateKey INTEGER)
PRIMARY INDEX ( AverageRate );

CREATE MULTISET TABLE AdventureWorksDW2019.ProspectiveBuyer ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      ProspectiveBuyerKey INTEGER NOT NULL,
      ProspectAlternateKey VARCHAR(30) CHARACTER SET UNICODE CASESPECIFIC,
      FirstName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      MiddleName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      LastName VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      BirthDate TIMESTAMP(0),
      MaritalStatus CHAR(2) CHARACTER SET UNICODE CASESPECIFIC,
      Gender VARCHAR(2) CHARACTER SET UNICODE CASESPECIFIC,
      EmailAddress VARCHAR(100) CHARACTER SET UNICODE CASESPECIFIC,
      YearlyIncome DECIMAL(19,4),
      TotalChildren INTEGER,
      NumberChildrenAtHome INTEGER,
      Education VARCHAR(80) CHARACTER SET UNICODE CASESPECIFIC,
      Occupation VARCHAR(200) CHARACTER SET UNICODE CASESPECIFIC,
      HouseOwnerFlag CHAR(2) CHARACTER SET UNICODE CASESPECIFIC,
      NumberCarsOwned INTEGER,
      AddressLine1 VARCHAR(240) CHARACTER SET UNICODE CASESPECIFIC,
      AddressLine2 VARCHAR(240) CHARACTER SET UNICODE CASESPECIFIC,
      City VARCHAR(60) CHARACTER SET UNICODE CASESPECIFIC,
      StateProvinceCode VARCHAR(6) CHARACTER SET UNICODE CASESPECIFIC,
      PostalCode VARCHAR(30) CHARACTER SET UNICODE CASESPECIFIC,
      Phone VARCHAR(40) CHARACTER SET UNICODE CASESPECIFIC,
      Salutation VARCHAR(16) CHARACTER SET UNICODE CASESPECIFIC,
      Unknown INTEGER, 
PRIMARY KEY ( ProspectiveBuyerKey ))
;
